const { GoogleGenerativeAI } = require("@google/generative-ai");

/**
 * List of preferred Gemini models in order of priority.
 * Primary: gemini-3.5-flash (active, current stable model).
 */
const PREFERRED_MODELS = [
  "gemini-3.5-flash",
  "gemini-3.1-flash-lite",
  "gemini-2.0-flash",
  "gemini-flash-latest",
];

/**
 * Dynamically fetches available generateContent models for the provided API key
 * as a fallback if preferred models fail.
 * @param {string} apiKey 
 * @returns {Promise<string[]>} List of model names
 */
const discoverAvailableModels = async (apiKey) => {
  try {
    const url = `https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`;
    const res = await fetch(url);
    const data = await res.json();
    if (data.models && Array.isArray(data.models)) {
      return data.models
        .filter((m) => m.supportedGenerationMethods?.includes("generateContent"))
        .map((m) => m.name.replace(/^models\//, ""));
    }
  } catch (err) {
    console.warn("Could not dynamically list Gemini models:", err.message);
  }
  return PREFERRED_MODELS;
};

/**
 * Service to generate property description using Google Gemini API.
 * @param {string} promptText - The prompt string generated by promptBuilder
 * @returns {Promise<string>} Generated description text
 */
const generateDescriptionFromGemini = async (promptText) => {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey || apiKey === "YOUR_API_KEY" || apiKey.trim() === "") {
    const error = new Error("GEMINI_API_KEY is missing or not configured in backend environment variables.");
    error.statusCode = 503;
    throw error;
  }

  const genAI = new GoogleGenerativeAI(apiKey);

  let candidateModels = [...PREFERRED_MODELS];

  let lastError = null;

  for (let i = 0; i < candidateModels.length; i++) {
    const modelName = candidateModels[i];
    try {
      const model = genAI.getGenerativeModel({ model: modelName });
      const result = await model.generateContent(promptText);
      const response = await result.response;
      let text = response.text();

      if (!text || typeof text !== "string" || !text.trim()) {
        throw new Error("Received an empty response from Gemini API.");
      }

      // Clean up any stray markdown formatting (e.g. bolding, header symbols, asterisks)
      text = text
        .replace(/\*\*|\*/g, "") // remove markdown bold/italics
        .replace(/^#+\s*/gm, "") // remove markdown headings
        .replace(/[\r\n]+/g, " ") // replace newlines with single space for a single paragraph
        .trim();

      return text;
    } catch (error) {
      console.warn(`Gemini model '${modelName}' attempt failed:`, error.message || error);

      const errMessage = error.message || "";

      // If invalid API Key, fail fast with 401
      if (errMessage.includes("API_KEY_INVALID") || errMessage.includes("API key not valid")) {
        const customErr = new Error("Invalid Gemini API key provided. Please check your GEMINI_API_KEY environment variable.");
        customErr.statusCode = 401;
        throw customErr;
      }

      // If Rate limit, fail fast with 429
      if (errMessage.includes("429") || errMessage.includes("RESOURCE_EXHAUSTED") || errMessage.includes("Quota exceeded")) {
        const customErr = new Error("Gemini API rate limit exceeded. Please wait a moment and try again.");
        customErr.statusCode = 429;
        throw customErr;
      }

      lastError = error;

      // If 404 / no longer available, attempt dynamic discovery if at last preferred model
      if (
        (errMessage.includes("404") || errMessage.includes("no longer available") || errMessage.includes("not found")) &&
        i === candidateModels.length - 1
      ) {
        const discovered = await discoverAvailableModels(apiKey);
        const newModels = discovered.filter((m) => !candidateModels.includes(m));
        if (newModels.length > 0) {
          candidateModels.push(...newModels);
        }
      }
    }
  }

  // Handle ultimate failure after all model attempts
  const errMessage = lastError?.message || "";
  let finalMessage = "Failed to generate property description via Gemini API.";
  let statusCode = 500;

  if (errMessage.includes("404") || errMessage.includes("no longer available") || errMessage.includes("not found")) {
    finalMessage = "All requested Gemini models are unavailable or unsupported for this API key.";
    statusCode = 404;
  } else if (errMessage.includes("503") || errMessage.includes("Service Unavailable")) {
    finalMessage = "Gemini API service is temporarily unavailable due to high demand. Please try again shortly.";
    statusCode = 503;
  }

  const finalError = new Error(finalMessage);
  finalError.statusCode = statusCode;
  throw finalError;
};

module.exports = {
  generateDescriptionFromGemini,
};
